apiVersion: apps/v1
kind: Deployment
metadata:
  name: saber
  namespace: blade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saber
  template:
    metadata:
      labels:
        app: saber
    spec:
      containers:
        - name: saber
          image: $image
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: saber
  namespace: blade
spec:
  ports:
    - port: 80
      targetPort: 80
      name: saber
      nodePort: 30009
  selector:
    app: saber
  type: NodePort
